version: '3.9'
services:
  backend:
    container_name: yearbook_backend
    image: yearbook/yearbook_backend_img
    build: .
    ports:
      - "8080:8080"
    networks:
      - yearbook_network
networks:
  yearbook_network:
    name: YEAR_NET